# Generated by Django 5.2.12 on 2026-03-15 14:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1980), django.core.validators.MaxValueValidator(2026)])),
                ('horsepower', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
            ],
            options={
                'ordering': ['brand', 'model'],
            },
        ),
    ]
